name: Bookstore

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install UV
      run: |
        python -m pip install --upgrade pip
        uv sync --all-extras --dev

    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Run tests
      run: pytest
